import Head from "next/head";

export default function HomeTitle() {
    return (
        <Head>
            <title>Cookie Stand Admin | Home Page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}