import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react';
// import styles from '../styles/Home.module.css'
import Logo from '../public/logo.png'

export default function Home() {
  const today = new Date();
  const year = today.getFullYear();
  const [cookiesStands, setCookiesStands] = useState([]);
  function handleUserQuestion(e) {
    e.preventDefault();
    const cookieStandData = {
      location: e.target.location.value,
      minCustomers: e.target.minimum_pre_hour.value,
      maxCustomers: e.target.maximum_pre_hour.value,
      avgCustomer: e.target.average_cookies_pre_sale.value,
      number: cookiesStands.length + 1,
    }

    setCookiesStands([...cookiesStands, cookieStandData])



  }
  return (
    <>
      {/* <div className={styles.container}> */}
      <Head>
        <title>Cookie Stand Admin | Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="">

        <nav className="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900">
          <div className="container flex flex-wrap justify-between items-center mx-auto">
            <a href="/" className="flex items-center mb-4 sm:mb-0">
              <Image src={Logo}
                alt="Landscape picture"
                width={50}
                height={50} />
              <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Cookie Stand</span>
            </a>
            <button data-collapse-toggle="navbar-default" type="button" className="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
              <span className="sr-only">Open main menu</span>
            </button>
            <div className="hidden w-full md:block md:w-auto" id="navbar-default">
              <ul className="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                  <a href="#" className="block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white" aria-current="page">Home</a>
                </li>
                <li>
                  <a href="#" className="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Report</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

      </header>
      <main className='flex flex-col '>
        <form className="mx-auto my-4 flex-col-reverse  w-86 bg-gray-200 p-2  rounded-lg " onSubmit={handleUserQuestion} >
          <div className="mb-6   justify-center p-2">
            <label htmlFor="location" className="block mb-2 text-sm font-medium">Location</label>
            <input type="text" id="location" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Amman" required />
          </div>

          <div className="mb-6 flex justify-center p-2" >
            <div className=" p-2">
              <label htmlFor="minimum_pre_hour" className="block mb-2 text-sm font-medium ">Minimum Customers Per Hour</label>
              <input type="number" id="minimum_pre_hour" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block  w-full  p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="0" required />

            </div>
            <div className=" p-2">
              <label htmlFor="maximum_pre_hour" className="block mb-2 text-sm font-medium"> Maximum Customers Per Hour</label>
              <input type="number" id="maximum_pre_hour" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block  w-full  p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="0" required />

            </div >
            <div className=" p-2">
              <label htmlFor="average_cookies_pre_sale" className="block mb-2 text-sm font-medium">Average Cookies Per Sale</label>
              <input type="number" id="average_cookies_pre_sale" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block  w-full  p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="1.0" required />

            </div>

          </div>
          {/* <input className="text-gray-50 bg-gray-600 px-2 py-1 rounded-lg " type="submit" value="Create" /> */}

          <button type="submit" className=" text-white bg-blue-100 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Create</button>

        </form>
        {/* <br /> */}
        <div className="mb-6 flex justify-center" >
          <p className='mx-auto'>
            Report table coming soon
          </p>
        </div>

        <div className="mb-6 " >
          <ul className="flex flex-wrap justify-center items-center text-gray-900 dark:text-white w-1/2  mx-auto my-4 ">

            {
              cookiesStands.map(item => {
                return (
                  <>
                    <li className='flex dark:text-black w-' key={item.number} >
                      {`{ Location: ${item.location}, minCustomers: ${item.minCustomers}, maxCustomers: ${item.maxCustomers},avgCustomer: ${item.avgCustomer}}`}
                    </li> <br />
                  </>
                )
              })
            }
          </ul>

        </div>

      </main>


      <footer className="p-4 bg-white rounded-lg shadow md:px-6 md:py-8 dark:bg-gray-900">
        <div className="sm:flex sm:items-center sm:justify-between">
          <a href="/" className="flex items-center mb-4 sm:mb-0">
            <Image src={Logo}
              alt="Landscape picture"
              width={100}
              height={100} />
            <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Cookie Stand</span>
          </a>
          <ul className="flex flex-wrap items-center mb-6 text-sm text-gray-500 sm:mb-0 dark:text-gray-400">
            <li>
              <a href="#" className="mr-4 hover:underline md:mr-6 ">Home</a>
            </li>
            <li>
              <a href="#" className="mr-4 hover:underline md:mr-6 ">Report</a>
            </li>
          </ul>
        </div>
        <hr className="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
        <span className="block text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2022 <Link href="/" className="hover:underline">Cookie Stand™</Link>. All Rights Reserved.
        </span>
      </footer>

    </>

  )
}
